In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [4]:
df=pd.read_csv('eda_data.csv')

In [5]:
df.head()

,Unnamed: 0,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,condition,sqft_above,sqft_basement,city,age,age_since_reno
0,0,2014-05-02,313000.0,3.0,1.50,1340,7912,1.5,3,1340,0,Shoreline,65,15
1,1,2014-05-02,342000.0,3.0,2.00,1930,11947,1.0,4,1930,0,Kent,54,0
2,2,2014-05-02,420000.0,3.0,2.25,2000,8030,1.0,4,1000,1000,Bellevue,57,0
3,3,2014-05-02,550000.0,4.0,2.50,1940,10500,1.0,4,1140,800,Redmond,44,28
4,4,2014-05-02,490000.0,2.0,1.00,880,6380,1.0,3,880,0,Seattle,82,26

In [6]:
df.columns

Index(['Unnamed: 0', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'condition', 'sqft_above', 'sqft_basement',
       'city', 'age', 'age_since_reno'],
      dtype='object')

In [7]:
#choosing relevant columns
df_model=df[['price', 'bedrooms', 'bathrooms', 'sqft_living','sqft_lot', 'floors', 'condition', 'sqft_above', 'sqft_basement','city', 'age', 'age_since_reno']]

In [8]:
#one hot encoding
df_dum=pd.get_dummies(df_model)
df_dum

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,condition,sqft_above,sqft_basement,age,...,city_SeaTac,city_Seattle,city_Shoreline,city_Skykomish,city_Snoqualmie,city_Snoqualmie Pass,city_Tukwila,city_Vashon,city_Woodinville,city_Yarrow Point
0,313000.000000,3.0,1.50,1340,7912,1.5,3,1340,0,65,...,0,0,1,0,0,0,0,0,0,0
1,342000.000000,3.0,2.00,1930,11947,1.0,4,1930,0,54,...,0,0,0,0,0,0,0,0,0,0
2,420000.000000,3.0,2.25,2000,8030,1.0,4,1000,1000,57,...,0,0,0,0,0,0,0,0,0,0
3,550000.000000,4.0,2.50,1940,10500,1.0,4,1140,800,44,...,0,0,0,0,0,0,0,0,0,0
4,490000.000000,2.0,1.00,880,6380,1.0,3,880,0,82,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3281,308166.666667,3.0,1.75,1510,6360,1.0,4,1510,0,66,...,0,1,0,0,0,0,0,0,0,0
3282,534333.333333,3.0,2.50,1460,7573,2.0,3,1460,0,37,...,0,0,0,0,0,0,0,0,0,0
3283,416904.166667,3.0,2.50,3010,7014,2.0,3,3010,0,11,...,0,0,0,0,0,0,0,0,0,0
3284,203400.000000,4.0,2.00,2090,6630,1.0,3,1070,1020,46,...,0,1,0,0,0,0,0,0,0,0
3285,220600.000000,3.0,2.50,1490,8102,2.0,4,1490,0,30,...,0,0,0,0,0,0,0,0,0,0

In [2]:
from sklearn.model_selection import train_test_split

In [9]:

X=df_dum.drop('price',axis=1)
y=df_dum.price.values

In [10]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [11]:
#multiple linear regression
import statsmodels.api as sm

In [12]:
X_sm=X=sm.add_constant(X)
model=sm.OLS(y,X_sm)
model.fit().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.673
Model:                            OLS   Adj. R-squared:                  0.667
Method:                 Least Squares   F-statistic:                     127.8
Date:                Wed, 09 Dec 2020   Prob (F-statistic):               0.00
Time:                        17:04:24   Log-Likelihood:                -42915.
No. Observations:                3286   AIC:                         8.594e+04
Df Residuals:                    3233   BIC:                         8.626e+04
Df Model:                          52
Covariance Type:            nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
const                    -2.905e+04   2.01e+04     -1.442      0.149   -6.85e+04    1.04e+04
bedrooms                 -2.198e+04   3359.183     -6.544      0.000   -2.86e+04   -1.54e+04
bathrooms                 3.169e+04   5280.165      6.002      0.000    2.13e+04     4.2e+04
sqft_living                 98.5578      3.546     27.794      0.000      91.605     105.510
sqft_lot                    -2.6968      0.773     -3.487      0.000      -4.213      -1.181
floors                    1.509e+04   6067.342      2.487      0.013    3191.056     2.7e+04
condition                 2.083e+04   3635.120      5.730      0.000    1.37e+04     2.8e+04
sqft_above                  80.9991      3.561     22.746      0.000      74.017      87.981
sqft_basement               17.5587      4.686      3.747      0.000       8.371      26.746
age                       1021.5700    112.080      9.115      0.000     801.815    1241.325
age_since_reno            -183.2192    217.010     -0.844      0.399    -608.710     242.271
city_Algona              -1.436e+05   5.66e+04     -2.535      0.011   -2.55e+05   -3.26e+04
city_Auburn              -1.332e+05   1.31e+04    -10.168      0.000   -1.59e+05   -1.08e+05
city_Beaux Arts Village   3.985e+05   1.12e+05      3.544      0.000    1.78e+05    6.19e+05
city_Bellevue             1.953e+05   1.18e+04     16.511      0.000    1.72e+05    2.19e+05
city_Black Diamond        2.857e+04   4.65e+04      0.614      0.539   -6.27e+04     1.2e+05
city_Bothell              2.883e+04   2.18e+04      1.321      0.187    -1.4e+04    7.16e+04
city_Burien              -7.696e+04    1.8e+04     -4.280      0.000   -1.12e+05   -4.17e+04
city_Carnation           -8.101e+04   4.66e+04     -1.739      0.082   -1.72e+05    1.03e+04
city_Clyde Hill           4.622e+05   6.54e+04      7.067      0.000    3.34e+05     5.9e+05
city_Covington           -1.414e+05   2.05e+04     -6.885      0.000   -1.82e+05   -1.01e+05
city_Des Moines          -1.075e+05   2.05e+04     -5.244      0.000   -1.48e+05   -6.73e+04
city_Duvall              -4.347e+04   2.28e+04     -1.903      0.057   -8.83e+04    1320.697
city_Enumclaw            -1.196e+05   3.11e+04     -3.845      0.000   -1.81e+05   -5.86e+04
city_Fall City            2.319e+04   6.53e+04      0.355      0.723   -1.05e+05    1.51e+05
city_Federal Way         -1.315e+05    1.3e+04    -10.097      0.000   -1.57e+05   -1.06e+05
city_Inglewood-Finn Hill  5.383e+04   1.13e+05      0.478      0.632   -1.67e+05    2.74e+05
city_Issaquah             1.039e+05   1.31e+04      7.914      0.000    7.81e+04     1.3e+05
city_Kenmore              1.655e+04   1.72e+04      0.961      0.337   -1.72e+04    5.03e+04
city_Kent                -1.184e+05   1.24e+04     -9.577      0.000   -1.43e+05   -9.41e+04
city_Kirkland             1.182e+05   1.24e+04      9.543      0.000    9.39e+04    1.42e+05
city_Lake Forest Park    -1.486e+04   2.39e+04     -0.621      0.535   -6.18e+04    3.21e+04
city_Maple Valley        -1.102e+05    1.5e+04     -7.350      0.000    -1.4e+05   -8.08e+04
city_Medina              -3.972e+05   1.13e+05     -3.525      0.000   -6.18e+05   -1.76e+05
city_Mercer Island        2.978e+05   2.04e+04     14.628      0.000    2.58e+05    3.38e+05
city_Milton              -9633.2846   7.97e+04     -0.121      0.904   -1.66e+05    1.47e+05
city_Newcastle            7.823e+04   2.45e+04      3.197      0.001    3.02e+04    1.26e+05
city_Normandy Park       -1.343e+04   3.65e+04     -0.368      0.713   -8.49e+04    5.81e+04
city_North Bend           -1.16e+04   2.35e+04     -0.493      0.622   -5.77e+04    3.45e+04
city_Pacific             -9.601e+04   4.66e+04     -2.062      0.039   -1.87e+05   -4714.211
city_Preston             -4825.4957   1.13e+05     -0.043      0.966   -2.26e+05    2.16e+05
city_Ravensdale          -8.701e+04   1.12e+05     -0.774      0.439   -3.08e+05    1.34e+05
city_Redmond              1.521e+05   1.23e+04     12.366      0.000    1.28e+05    1.76e+05
city_Renton              -6.553e+04   1.11e+04     -5.885      0.000   -8.74e+04   -4.37e+04
city_Sammamish            1.097e+05   1.34e+04      8.170      0.000    8.34e+04    1.36e+05
city_SeaTac              -1.061e+05   2.53e+04     -4.193      0.000   -1.56e+05   -5.65e+04
city_Seattle              1.046e+05   9917.670     10.543      0.000    8.51e+04    1.24e+05
city_Shoreline            -798.5551   1.38e+04     -0.058      0.954   -2.78e+04    2.62e+04
city_Skykomish           -1.927e+05   1.13e+05     -1.709      0.087   -4.14e+05    2.83e+04
city_Snoqualmie          -1.765e+04   1.92e+04     -0.921      0.357   -5.52e+04    1.99e+04
city_Snoqualmie Pass      1.086e+05   1.12e+05      0.965      0.334   -1.12e+05    3.29e+05
city_Tukwila             -1.236e+05   2.44e+04     -5.055      0.000   -1.72e+05   -7.57e+04
city_Vashon               -4.18e+04   5.67e+04     -0.737      0.461   -1.53e+05    6.95e+04
city_Woodinville          4.521e+04   1.86e+04      2.426      0.015    8668.615    8.18e+04
city_Yarrow Point         3.538e+04   8.01e+04      0.442      0.659   -1.22e+05    1.92e+05
==============================================================================
Omnibus:                      350.554   Durbin-Watson:                   1.793
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2590.554
Skew:                          -0.206   Prob(JB):                         0.00
Kurtosis:                       7.330   Cond. No.                     9.86e+18
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 2.41e-27. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [13]:
from sklearn.linear_model import LinearRegression,Lasso
from sklearn.model_selection import cross_val_score

In [14]:
lm=LinearRegression()
lm.fit(X_train,y_train)

LinearRegression()

In [15]:
np.mean(cross_val_score(lm,X_train,y_train,scoring='neg_mean_absolute_error',cv=3))

-81920.04312225195

In [ ]:
#lasso regression
alpha=[]
error=[]
for i in range(1,1000):
    alpha.append(i/100)
    lml=Lasso(alpha=(i/100))
    error.append(np.mean(cross_val_score(lml,X_train,y_train,scoring='neg_mean_absolute_error',cv=3)))
plt.plot(alpha,error)

In [ ]:
err=tuple(zip(alpha,error))
df_err=pd.DataFrame(err,columns=['alpha','error'])
df_err[df_err.error==max(df_err.error)]

In [16]:
#random forest
from sklearn.ensemble import RandomForestRegressor
rf=RandomForestRegressor()
np.mean(cross_val_score(rf,X_train,y_train,scoring='neg_mean_absolute_error',cv=3))

-82007.25857281355

In [17]:
#tune models GridSearchCV
from sklearn.model_selection import GridSearchCV

In [18]:
parameters={'n_estimators':range(10,300,10),'criterion':('mse','mae'),'max_features':('auto','sqrt','log2')}

In [19]:
gs=GridSearchCV(rf,parameters,scoring='neg_mean_absolute_error',cv=3,n_jobs=15)
gs.fit(X_train,y_train)

GridSearchCV(cv=3, estimator=RandomForestRegressor(), n_jobs=15,
             param_grid={'criterion': ('mse', 'mae'),
                         'max_features': ('auto', 'sqrt', 'log2'),
                         'n_estimators': range(10, 300, 10)},
             scoring='neg_mean_absolute_error')

In [20]:
gs.best_score_

-81375.86768478218

In [21]:
gs.best_estimator_

RandomForestRegressor(n_estimators=160)

In [22]:
#test ensembles
tpred_lm=lm.predict(X_test)
tpred_rf=gs.best_estimator_.predict(X_test)

In [23]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test,tpred_lm)
mean_absolute_error(y_test,tpred_rf)

73901.11968861263

In [24]:
mean_absolute_error(y_test,(tpred_lm+tpred_rf)/2)

72826.08631836846